on:
  workflow_run:
    workflows: 
      - Tests
    branches:
      - main
    types: 
      - completed

jobs:
  upload_files:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: main
    runs-on: ubuntu-latest
    name: Build and upload files
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install environment
        run: bash create_env.sh
      - name: Build language
        run: bash make.sh
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './demo'
          remotePath: './startupoptionsbot.com'
