name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install environment
        run: bash create_env.sh
      - name: Install browser
        run: bash install_browser.sh
      - name: Build language
        run: bash make.sh
      - name: Compile with Grunt
        uses: elstudio/actions-js-build/build@v4